#! /usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(prog='task-cli', 
                                     description='A CLI Task list',)
    subparsers = parser.add_subparsers(required=True)

    parser_add = subparsers.add_parser('add',help='Command to add a task')
    parser_add.add_argument('description',type=str,help='Description of task you are adding')

    parser_update = subparsers.add_parser('update',help='Command to update an existing task')
    parser_update.add_argument('task_id',type=int,help='The id number of the task you want to update')
    parser_update.add_argument('description',type=str,help='Description of the task you are updating')
    

    args = parser.parse_args()

if __name__ == '__main__':
    main()
